// Generated by IB v0.1.4 gem. Do not edit it manually
// Run `rake design` to refresh

#import "Stubs.h"

@implementation ListController

@end


@implementation NewController

@end


@implementation RootController

@end

