// Generated by IB v0.1.4 gem. Do not edit it manually
// Run `rake design` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface ListController : UITableViewController

@property IBOutlet id users;
@property IBOutlet UITableViewCell * cell;



-(IBAction) viewDidLoad;

@end


@interface NewController : UIViewController

@property IBOutlet UIButton * save;
@property IBOutlet UITextField * username;
@property IBOutlet UITextField * password;



-(IBAction) viewDidLoad;
-(IBAction) btn_save;
-(IBAction) doneEdit:(id) sender;

@end


@interface RootController : UITabBarController







@end

